server:
  port: 8888
spring:
  profiles:
    active:
      - remote_repo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AnatoliyYakimov/spmia_config_repo/
          searchPaths: licensingservice, organizationservice